apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-http" .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - name: grpc
      port: 8090
      targetPort: 8090
      nodePort: 30534
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Values.name }}