apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/instance: leader-election-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: nanhu-infer
    app.kubernetes.io/part-of: nanhu-infer
    app.kubernetes.io/managed-by: helm
  name: nanhu-infer-leader-election-rolebinding
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nanhu-infer-leader-election-role
subjects:
- kind: ServiceAccount
  name: nanhu-infer-controller
  namespace: {{ .Values.namespace }}
