apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - port: 65532
      targetPort: 65532
      nodePort: 30532
      protocol: TCP
      name: controller
  selector:
    app.kubernetes.io/name: {{ .Values.name }}